runtime: go
api_version: go1.8

handlers:
    - url: /.*
      script: _go_app

nobuild_files:
    - handler
      sheets

instance_class: B1
basic_scaling:
    max_instances: 1
    idle_timeout: 10m
