runtime: go
api_version: go1.8

handlers:
    - url: /.*
      script: _go_app

nobuild_files:
    - handler
      sheets

threadsafe: true
instance_class: F1
automatic_scaling:
    min_idle_instances: automatic
    max_idle_instances: 0
    min_pending_latency: 3000ms
    max_pending_latency: automatic
